name = "Hugo Split Gallery"
license = "GPL-3.0-or-later"
licenselink = "https://gitlab.com/tmuguet/hugo-split-gallery/-/blob/main/LICENSE"
description = "Photo gallery inspired by Hugo Split Theme"
homepage = "https://edbe777.github.io/maps_website/"
tags = ["blog", "gallery", "responsive"]
features = ["posts"]

[author]
  name = "Ed"
  homepage = "https://edbe777.github.io/maps_website/"
